# Generated by Django 3.1.3 on 2020-11-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='originalVid',
            fields=[
                ('video_url', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaptername', models.CharField(max_length=200)),
                ('chaptertime', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='topWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('count', models.IntegerField()),
                ('appearance_time1', models.IntegerField(default=0)),
                ('appearance_time2', models.IntegerField(default=0)),
                ('appearance_time3', models.IntegerField(default=0)),
                ('appearance_time4', models.IntegerField(default=0)),
                ('appearance_time5', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('joy', models.IntegerField(default=0)),
                ('sad', models.IntegerField(default=0)),
                ('disappoint', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('teasing', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('questionmark', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='highlightVid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='chatFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('num_of_chat', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=30)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='audioFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('decibel', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
    ]
