# Generated by Django 3.1.3 on 2020-11-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalvid',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
