# Generated by Django 3.1.3 on 2020-11-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalvid',
            name='crawlingState',
            field=models.BooleanField(default=False),
        ),
    ]
