# Generated by Django 3.1.3 on 2020-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0002_originalvid_crawlingstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchchapter',
            name='chaptertime',
        ),
        migrations.AddField(
            model_name='twitchchapter',
            name='endTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitchchapter',
            name='staetTime',
            field=models.IntegerField(default=0),
        ),
    ]
