# Generated by Django 3.1.3 on 2020-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
