# Generated by Django 3.1.3 on 2020-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0003_auto_20201116_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchchapter',
            old_name='staetTime',
            new_name='startTime',
        ),
    ]
