# Generated by Django 3.1.3 on 2020-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0003_auto_20201113_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalvid',
            name='downloadState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='originalvid',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
