# Generated by Django 3.1.3 on 2020-11-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0004_auto_20201115_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchapter',
            name='chapterID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
