# Generated by Django 3.1.3 on 2020-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0004_auto_20201116_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightvid',
            name='chapter',
            field=models.CharField(default='demo', max_length=50),
        ),
    ]
