# Generated by Django 3.1.3 on 2020-11-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0005_twitchchapter_chapterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightvid',
            name='highlightID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
