# Generated by Django 3.1.3 on 2020-11-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0005_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('decibel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chatFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('num_of_chat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='highlightVid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='originalVid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='topWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('appearance_time', models.CharField(max_length=20)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='React',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.user'),
        ),
        migrations.AddField(
            model_name='record',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid'),
        ),
        migrations.AddField(
            model_name='highlightvid',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid'),
        ),
        migrations.AddField(
            model_name='chatflow',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid'),
        ),
        migrations.AddField(
            model_name='audioflow',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid'),
        ),
    ]
