# Generated by Django 3.1.3 on 2020-11-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0006_auto_20201106_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioflow',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='chatflow',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='highlightvid',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='topwords',
            old_name='video_id',
            new_name='video',
        ),
    ]
