# Generated by Django 3.1.3 on 2020-11-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0007_auto_20201108_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalvid',
            old_name='user_id',
            new_name='streamer',
        ),
    ]
