# Generated by Django 3.1.3 on 2020-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0008_auto_20201109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioflow',
            name='decibel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audioflow',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='num_of_chat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highlightvid',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highlightvid',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topwords',
            name='appearance_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topwords',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
