# Generated by Django 3.1.3 on 2020-11-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0009_auto_20201111_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='sentiment',
            name='disappoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='joy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='questionmark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='surprise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='teasing',
            field=models.IntegerField(default=0),
        ),
    ]
