# Generated by Django 3.1.3 on 2020-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0010_auto_20201111_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topwords',
            old_name='appearance_time',
            new_name='count',
        ),
        migrations.AddField(
            model_name='topwords',
            name='appearance_time1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topwords',
            name='appearance_time2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topwords',
            name='appearance_time3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topwords',
            name='appearance_time4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topwords',
            name='appearance_time5',
            field=models.IntegerField(default=0),
        ),
    ]
