# Generated by Django 3.1.3 on 2020-11-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0011_auto_20201111_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaptername', models.CharField(max_length=200)),
                ('chaptertime', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid')),
            ],
        ),
    ]
