# Generated by Django 3.1.3 on 2020-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0012_twitchchapter_twitchdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchchapter',
            name='chaptertime',
            field=models.CharField(max_length=200),
        ),
    ]
