# Generated by Django 3.1.3 on 2020-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0013_auto_20201112_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalvid',
            name='video_url',
            field=models.IntegerField(),
        ),
    ]
