# Generated by Django 3.1.3 on 2020-11-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0014_auto_20201112_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='originalvid',
            name='video_url',
            field=models.IntegerField(unique=True),
        ),
    ]
