# Generated by Django 3.1.3 on 2020-11-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0015_auto_20201112_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioflow',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='chatflow',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='highlightvid',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='topwords',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='twitchchapter',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
        migrations.AlterField(
            model_name='twitchdata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
        ),
    ]
