# Generated by Django 3.1.3 on 2020-11-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0016_auto_20201112_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioflow',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='chatflow',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='highlightvid',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='topwords',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='twitchchapter',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RenameField(
            model_name='twitchdata',
            old_name='video',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='video',
        ),
        migrations.AddField(
            model_name='record',
            name='video_url',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='youha.originalvid', to_field='video_url'),
            preserve_default=False,
        ),
    ]
