# Generated by Django 3.1.3 on 2020-11-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youha', '0017_auto_20201112_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioflow',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='chatflow',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='highlightvid',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='topwords',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='twitchchapter',
            old_name='video_url',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='twitchdata',
            old_name='video_url',
            new_name='video',
        ),
    ]
